// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BHapFnH_fuM4AOLTsEE_XNZhn90HzPs',
    appId: '1:787143359912:web:a8d98c42d8d67faacb319d',
    messagingSenderId: '787143359912',
    projectId: 'groupchat-e2c5a',
    authDomain: 'groupchat-e2c5a.firebaseapp.com',
    storageBucket: 'groupchat-e2c5a.appspot.com',
    measurementId: 'G-MEXLNFQL4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2tDI5Gx5Els33dp5ybQQuRv7iLxDDXp8',
    appId: '1:787143359912:android:12c76a461892b3becb319d',
    messagingSenderId: '787143359912',
    projectId: 'groupchat-e2c5a',
    storageBucket: 'groupchat-e2c5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3tYlXdcB8B1M-CgAz6YWwmIvvMo3Wqt0',
    appId: '1:787143359912:ios:d5ed8defed37cb17cb319d',
    messagingSenderId: '787143359912',
    projectId: 'groupchat-e2c5a',
    storageBucket: 'groupchat-e2c5a.appspot.com',
    iosBundleId: 'com.cleangroupchat.groupchatCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3tYlXdcB8B1M-CgAz6YWwmIvvMo3Wqt0',
    appId: '1:787143359912:ios:54f30de3c7a69c5bcb319d',
    messagingSenderId: '787143359912',
    projectId: 'groupchat-e2c5a',
    storageBucket: 'groupchat-e2c5a.appspot.com',
    iosBundleId: 'com.cleangroupchat.groupchatCleanArchitecture.RunnerTests',
  );
}
